##本地环境设置 配置注意事项 : 后面紧跟一个空格 然后再配置您的实际值
server:
  #tomcat端口  比如http://{ip}:{port}{/context-path}中的{port} 纯数字
  port: 18086
spring:
  profiles: localhost
  thymeleaf:
    cache: false
  datasource:
    #mysql url连接信息
    url: jdbc:mysql://localhost:3307/us?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&userSSL=true&serverTimezone=Hongkong&zeroDateTimeBehavior=CONVERT_TO_NULL
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #mysql8新驱动名称
    driverClassName: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    #所有的redis 缓存都会加入下面的前缀 方便管理
    keyPrefix: us-user.
    # redis地址 单机模式 参见RedisConfig
    host: localhost
    #redis端口 单机模式
    port: 6379
    #不允许redis密码为空字符串 可以不设置 您也可以使用"1234"
    password:
    #集群模式 默认不开启 因为集群模式redis配置复杂，演示版只有一个redis
    #        cluster:
    #redis支持集群模式(需要参考文档自行打开) 也支持单机(配置一个即可) 配置规则：节点的ip:port,ip:port 逗号分隔多个
#       nodes: localhost:6379
#           最大连接时间 具体参考JedisCluster官方文档
#           connectionTimeout: 5000
#           soTimeout: 5000
#           maxAttempts: 3

